### ISSUE TITLE
Compatibility with Magento 2.2

### ISSUE THREAD

**Issue by TheGuit** [mailjet/mailjet-magento2#1]
Hi,

Is there any chance that this module would works on Magento 2.2 ? I think that you haven't tested it, but one of our client would like to integrate this module and run actually a Magento 2.2 site, migration to Magento 2.3 is not planned for the moment.

My question is, have you announce compatibility to Magento 2.3+ because you use specific function of Magento 2.3, or because ou just haven't tested it on Magento 2.2 ?

Regards,

**Comment by ngarnier** [comment]
Hey @TheGuit, to provide a better experience, we are indeed using specific functions available only in Magento 2.3+ and therefore the extension is not compatible with Magento 2.2. 

We have no plan to make it compatible with Magento 2.2 at this time.

**Comment by nemul** [comment]
What about 2.4.2?

**Comment by ystuka** [comment]
Hey @nemul, сompatibility issues have been fixed and the extension is compatible with Magento 2.4.2 now
