### ISSUE TITLE
 Compatibility Mailjet - Magento EE 2.3 version?

### ISSUE THREAD

**Issue by manonveja** [mailjet/mailjet-magento2#3]
Hi! 
On the mailjet documentation it is stated that the mailjet-magento2 module is compatible with the magento EE 2.3 version.
During compilation, we encountered an error related to a class that does not exist in Magento 2.3.1 version (\Magento\Sales\Block\DataProviders\Email\Shipment\TrackingUrl), the compatibility of the mailjet-magento module is at least Magento EE 2.3.1?
Do you have a solution to this problem? 
Thanks!

**Comment by ppota-paul** [comment]
Solution:
https://github.com/mailjet/mailjet-magento2/pull/4
