### ISSUE TITLE
Compatibility with Magento 2.4.2

### ISSUE THREAD

**Issue by nemul** [mailjet/mailjet-magento2#6]
I have no problem to install the extension via composer on M2.4.1, but on 2.4.2 I get:

 [InvalidArgumentException]                                                                                                                                                                                                  
  Could not find a matching version of package mailjet/mailjet-magento2. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

**Comment by ystuka** [comment]
This issue was fixed.
