### ISSUE TITLE
Need renamed plugin name parameter "LOGIN" to "Login" or "login"

### ISSUE THREAD

**Issue by kevwis** [mailjet/mailjet-magento2#7]
On magento 2.4.3 module is not working 

A plugin by the name "LOGIN" was not found in the plugin manager Laminas\Mail\Protocol\SmtpPluginManager

please change usages here
https://github.com/mailjet/mailjet-magento2/blob/910092897baac7e4d34453b4056bdf7af1e4e6e8/Model/Framework/Mail/Transport.php#L42

\Laminas\Mail\Protocol\SmtpPluginManager => "LOGIN" key doest not exists

Usage need "Login" or "login":
		'login'   => Smtp\Auth\Login::class,
		'Login'   => Smtp\Auth\Login::class,

**Comment by ystuka** [comment]
This issue was fixed.
